name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Install Discloud CLI globally
        run: |
          npm install -g discloud
          echo "$(npm root -g)/.bin" >> $GITHUB_PATH  # Add Discloud CLI to PATH

      - name: Authenticate with Discloud
        env:
          PATH: ${{ env.PATH }}:$(npm root -g)/.bin
        run: discloud login --token ${{ secrets.DISCLOUD_TOKEN }}

      - name: Zip the bot files
        env:
          PATH: ${{ env.PATH }}:$(npm root -g)/.bin
        run: discloud zip

      - name: Deploy bot to Discloud
        env:
          PATH: ${{ env.PATH }}:$(npm root -g)/.bin
        run: discloud app upload
