name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          npm install discloud --save-dev  # Ensure Discloud is installed

      - name: Verify Discloud installation
        run: |
          npx discloud --version  # This will ensure that discloud is installed correctly

      - name: Authenticate with Discloud
        run: npx discloud login --token ${{ secrets.DISCLOUD_TOKEN }}

      - name: Zip the bot files
        run: npx discloud zip

      - name: Deploy bot to Discloud
        run: npx discloud app upload

