name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Adjust to your Node.js version

      - name: Install Discloud CLI globally
        run: npm install -g discloud

      - name: Authenticate with Discloud
        run: discloud login --token ${{ secrets.DISCLOUD_TOKEN }}

      - name: Zip the bot files
        run: discloud zip

      - name: Deploy bot to Discloud
        run: discloud app upload

